-- Smart Grocery List & Recipe Planner
-- Data Tier schema (PostgreSQL syntax; MySQL notes in comments where it differs)

DROP TABLE IF EXISTS user_lists CASCADE;
DROP TABLE IF EXISTS recipe_ingredients CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS ingredients CASCADE;

-- Master catalog of every ingredient the app knows about
CREATE TABLE ingredients (
  id         SERIAL PRIMARY KEY,          -- MySQL: INT AUTO_INCREMENT PRIMARY KEY
  name       VARCHAR(100) UNIQUE NOT NULL,
  unit       VARCHAR(20)  NOT NULL DEFAULT 'unit',   -- default unit, e.g. 'g', 'ml', 'unit'
  category   VARCHAR(50)  DEFAULT 'other'            -- produce, dairy, pantry, etc.
);

-- Recipes a user can plan meals from
CREATE TABLE recipes (
  id           SERIAL PRIMARY KEY,
  name         VARCHAR(150) NOT NULL,
  description  TEXT,
  servings     INT DEFAULT 4,
  instructions TEXT,
  created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Junction table: which ingredients (and how much) a recipe needs
CREATE TABLE recipe_ingredients (
  recipe_id     INT NOT NULL REFERENCES recipes(id)     ON DELETE CASCADE,
  ingredient_id INT NOT NULL REFERENCES ingredients(id)  ON DELETE CASCADE,
  quantity      NUMERIC(10,2) NOT NULL,
  unit          VARCHAR(20) NOT NULL,
  PRIMARY KEY (recipe_id, ingredient_id)
);

-- The user's live shopping list. Rows can originate from manual entry
-- or be auto-generated by the "plan a recipe" business logic.
CREATE TABLE user_lists (
  id            SERIAL PRIMARY KEY,
  ingredient_id INT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
  quantity      NUMERIC(10,2) NOT NULL DEFAULT 1,
  unit          VARCHAR(20) NOT NULL,
  is_checked      BOOLEAN NOT NULL DEFAULT FALSE,
  source        VARCHAR(150) NOT NULL DEFAULT 'manual', -- 'manual' or 'recipe:<name>'
  added_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_lists_ingredient ON user_lists(ingredient_id);
CREATE INDEX idx_recipe_ingredients_ingredient ON recipe_ingredients(ingredient_id);




-- Sample data so the app is usable immediately after setup

INSERT INTO ingredients (name, unit, category) VALUES
  ('Spaghetti',        'g',    'pantry'),
  ('Eggs',             'unit', 'dairy'),
  ('Parmesan cheese',  'g',    'dairy'),
  ('Pancetta',         'g',    'meat'),
  ('Black pepper',     'tsp',  'spice'),
  ('Chicken breast',   'g',    'meat'),
  ('Broccoli',         'g',    'produce'),
  ('Soy sauce',        'tbsp', 'pantry'),
  ('Garlic',           'clove','produce'),
  ('Rice',             'g',    'pantry'),
  ('Onion',            'unit', 'produce'),
  ('Olive oil',        'tbsp', 'pantry'),
  ('Tomato',           'unit', 'produce'),
  ('Basil',            'g',    'produce'),
  ('Mozzarella',       'g',    'dairy');

INSERT INTO recipes (name, description, servings, instructions) VALUES
  ('Spaghetti Carbonara', 'Classic Roman pasta with egg, cheese, and pancetta.', 2,
   'Cook spaghetti. Whisk eggs with parmesan and pepper. Crisp pancetta. Toss everything together off heat.'),
  ('Garlic Chicken Stir Fry', 'Quick weeknight stir fry with broccoli and rice.', 3,
   'Cook rice. Sear chicken. Add garlic and broccoli. Toss with soy sauce and serve over rice.'),
  ('Margherita Pizza', 'Simple tomato, basil, and mozzarella pizza.', 4,
   'Top dough with tomato, mozzarella, and basil. Bake until golden.');

-- Spaghetti Carbonara ingredients
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit)
SELECT r.id, i.id, v.quantity, v.unit FROM (VALUES
  ('Spaghetti Carbonara', 'Spaghetti', 200, 'g'),
  ('Spaghetti Carbonara', 'Eggs', 2, 'unit'),
  ('Spaghetti Carbonara', 'Parmesan cheese', 50, 'g'),
  ('Spaghetti Carbonara', 'Pancetta', 100, 'g'),
  ('Spaghetti Carbonara', 'Black pepper', 1, 'tsp')
) AS v(recipe_name, ingredient_name, quantity, unit)
JOIN recipes r ON r.name = v.recipe_name
JOIN ingredients i ON i.name = v.ingredient_name;

-- Garlic Chicken Stir Fry ingredients
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit)
SELECT r.id, i.id, v.quantity, v.unit FROM (VALUES
  ('Garlic Chicken Stir Fry', 'Chicken breast', 400, 'g'),
  ('Garlic Chicken Stir Fry', 'Broccoli', 200, 'g'),
  ('Garlic Chicken Stir Fry', 'Soy sauce', 3, 'tbsp'),
  ('Garlic Chicken Stir Fry', 'Garlic', 3, 'clove'),
  ('Garlic Chicken Stir Fry', 'Rice', 300, 'g')
) AS v(recipe_name, ingredient_name, quantity, unit)
JOIN recipes r ON r.name = v.recipe_name
JOIN ingredients i ON i.name = v.ingredient_name;

-- Margherita Pizza ingredients
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit)
SELECT r.id, i.id, v.quantity, v.unit FROM (VALUES
  ('Margherita Pizza', 'Tomato', 3, 'unit'),
  ('Margherita Pizza', 'Mozzarella', 200, 'g'),
  ('Margherita Pizza', 'Basil', 10, 'g'),
  ('Margherita Pizza', 'Olive oil', 2, 'tbsp')
) AS v(recipe_name, ingredient_name, quantity, unit)
JOIN recipes r ON r.name = v.recipe_name
JOIN ingredients i ON i.name = v.ingredient_name;
